version: '3.9'

services:

  #php+apache
  php:
    build: .
    container_name: backend
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - network
    ports:
      - "4080:80"
    volumes:
      - "./backend:/var/www/html"
    environment:
      FRONTEND_HOST: node:4080
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: database

  #node
  node:
    build: .
    container_name: frontend
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    command: bash -c "npm i && npm run serve"
    networks:
      - network
    ports:
      - "4081:8080"
    volumes:
      - "./frontend:/home/node/app"
    environment:
      BACK_HOST: php:4081/api
      CHOKIDAR_USEPOLLING: 'true'     
  
  #mysql
  mysql:
    image: mysql:8.0
    container_name: database
    networks:
      - network
    ports:
      - "3306:3306"
    volumes:
      - "./db:/home/bkp"
      - "mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: idr_database

  #phpmyadmin
  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    container_name: phpmyadmin
    networks:
      - network
    ports:
      - "4033:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306 

volumes:
  mysql_db:
    driver: "local"

networks:
  network:
    driver: bridge
